version: '3.7'
services:
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.10.2
    ports:
      - "3000:3000"
    restart: unless-stopped

  hydra:
    image: oryd/hydra:v1.10.2-sqlite
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
      - "4446:4446" # If using the user auth test endpoint
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./
        target: /etc/config/hydra
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - HYDRA_URL=http://127.0.0.1:4445
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate

  hydra-migrate:
    image: oryd/hydra:v1.10.2-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./
        target: /etc/config/hydra
    restart: on-failure

volumes:
  hydra-sqlite: