// Code generated by 'yaegi extract github.com/mbict/befe/dsl/jwt'. DO NOT EDIT.

package buildin

import (
	"context"
	"github.com/mbict/befe/dsl/jwt"
	"github.com/mbict/befe/expr"
	"reflect"
)

func init() {
	Symbols["github.com/mbict/befe/dsl/jwt/jwt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"HasJwtAudience":  reflect.ValueOf(jwt.HasJwtAudience),
		"HasJwtClaim":     reflect.ValueOf(jwt.HasJwtClaim),
		"HasJwtScopes":    reflect.ValueOf(jwt.HasJwtScopes),
		"JwkToken":        reflect.ValueOf(jwt.JwkToken),
		"JwtIsNotExpired": reflect.ValueOf(jwt.JwtIsNotExpired),
		"ParamFromClaim":  reflect.ValueOf(jwt.ParamFromClaim),
		"TokenFromCookie": reflect.ValueOf(jwt.TokenFromCookie),
		"TokenFromHeader": reflect.ValueOf(jwt.TokenFromHeader),
		"ValueFromClaim":  reflect.ValueOf(jwt.ValueFromClaim),

		// type definitions
		"Jwk":          reflect.ValueOf((*jwt.Jwk)(nil)),
		"TokenFetcher": reflect.ValueOf((*jwt.TokenFetcher)(nil)),

		// interface wrapper definitions
		"_Jwk": reflect.ValueOf((*_github_com_mbict_befe_dsl_jwt_Jwk)(nil)),
	}
}

// _github_com_mbict_befe_dsl_jwt_Jwk is an interface wrapper for Jwk type
type _github_com_mbict_befe_dsl_jwt_Jwk struct {
	IValue            interface{}
	WBuildHandler     func(ctx context.Context, next expr.Handler) expr.Handler
	WTokenFrom        func(tokenFetchers ...jwt.TokenFetcher) jwt.Jwk
	WWhenDenied       func(actions ...expr.Action) jwt.Jwk
	WWhenExpired      func(actions ...expr.Action) jwt.Jwk
	WWhenNoToken      func(actions ...expr.Action) jwt.Jwk
	WWithAudience     func(audiences ...string) jwt.Jwk
	WWithClaim        func(name string, values ...string) jwt.Jwk
	WWithExpiredCheck func() jwt.Jwk
}

func (W _github_com_mbict_befe_dsl_jwt_Jwk) BuildHandler(ctx context.Context, next expr.Handler) expr.Handler {
	return W.WBuildHandler(ctx, next)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) TokenFrom(tokenFetchers ...jwt.TokenFetcher) jwt.Jwk {
	return W.WTokenFrom(tokenFetchers...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WhenDenied(actions ...expr.Action) jwt.Jwk {
	return W.WWhenDenied(actions...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WhenExpired(actions ...expr.Action) jwt.Jwk {
	return W.WWhenExpired(actions...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WhenNoToken(actions ...expr.Action) jwt.Jwk {
	return W.WWhenNoToken(actions...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WithAudience(audiences ...string) jwt.Jwk {
	return W.WWithAudience(audiences...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WithClaim(name string, values ...string) jwt.Jwk {
	return W.WWithClaim(name, values...)
}
func (W _github_com_mbict_befe_dsl_jwt_Jwk) WithExpiredCheck() jwt.Jwk {
	return W.WWithExpiredCheck()
}
